imagePullSecrets:
  - name: docker-subshell

sophora:
  serverUrl: http://cluster-01-sophora-server:1196
  authentication:
    secret:
      name: "sophora-user-admin-credentials"
      usernameKey: "username"
      passwordKey: "password"

exporter:
  config:
    deltaExport: true
    exportDocumentsWithTimestamp: true
    documents:
      - uuids:
          - "f467d50d-ed80-4722-ae9b-746f2e6dce89"
        "exportRelevantStructure": false
        "exportRelevantIndexDocuments": false
        "exportRelevantHierarchyDocuments": false

s3:
  name: "sophora-test-importer"
  url: "https://storage.googleapis.com"
  secret:
    name: "sophora-importer-bucket-credentials"