apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sophora-repo-import.fullname" . }}
  labels: {{- include "sophora-repo-import.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      shareProcessNamespace: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.repoDownload.zipViaHttp.zipUrls }}
        - name: zip-via-http-downloader
          image: "{{ .Values.repoDownload.zipViaHttp.image.repository }}:{{ .Values.repoDownload.zipViaHttp.image.tag }}"
          imagePullPolicy: {{ .Values.repoDownload.zipViaHttp.image.pullPolicy }}
          volumeMounts:
            - mountPath: /import
              name: import
            - mountPath: /metrics
              name: metrics
          env:
            - name: REPO_ZIP_URLS
              value: {{ include "sophora-repo-import.utils.joinListWithSpace" .Values.repoDownload.zipViaHttp.zipUrls | quote }}
            - name: HTTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaHttp.usernameKey | quote }}
                  name: {{ .Values.repoDownload.zipViaHttp.secretName | quote }}
            - name: HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaHttp.passwordKey }}
                  name: {{ .Values.repoDownload.zipViaHttp.secretName | quote }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |- {{- .Files.Get "download-files-via-http.sh" | nindent 14 }}
        {{- end }}
        {{- if .Values.repoDownload.zipViaS3.zipPaths }}
        - name: zip-via-s3-downloader
          image: "{{ .Values.repoDownload.zipViaS3.image.repository }}:{{ .Values.repoDownload.zipViaS3.image.tag }}"
          imagePullPolicy: {{ .Values.repoDownload.zipViaS3.image.pullPolicy }}
          volumeMounts:
            - mountPath: /import
              name: import
            - mountPath: /metrics
              name: metrics
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaS3.accessKeyIdKey }}
                  name: {{ .Values.repoDownload.zipViaS3.secretName }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaS3.secretAccessKeyKey }}
                  name: {{ .Values.repoDownload.zipViaS3.secretName }}
            - name: S3_ENDPOINT
              value: {{ .Values.repoDownload.zipViaS3.s3Endpoint }}
            - name: S3_NAME
              value: {{.Values.repoDownload.zipViaS3.bucketName }}
            - name: S3_FILE_PATHS
              value: {{ include "sophora-repo-import.utils.joinListWithSpace" .Values.repoDownload.zipViaS3.zipPaths | quote }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |- {{- .Files.Get "download-files-via-s3.sh" | nindent 14 }}
        {{- end }}
      containers:
        - name: importer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |- {{- .Files.Get "run-importer.sh" | nindent 14 }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: {{ .Values.javaOptions }}
            - name: SOPHORA_CLIENT_SERVERCONNECTION_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{.Values.sophora.authentication.secret.usernameKey}}
                  name: {{.Values.sophora.authentication.secret.name}}
            - name: SOPHORA_CLIENT_SERVERCONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{.Values.sophora.authentication.secret.passwordKey}}
                  name: {{.Values.sophora.authentication.secret.name}}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: importer-config
              mountPath: /sophora/application.yml
              subPath: application.yml
            - name: import
              mountPath: /import
            - mountPath: /metrics
              name: metrics
        - name: process-watcher
          image: "{{ .Values.processWatcherImage.repository }}:{{ .Values.processWatcherImage.tag }}"
          imagePullPolicy: {{ .Values.processWatcherImage.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |- {{ .Files.Get "wait-for-empty-dir.sh" | nindent 14 }}
          volumeMounts:
            - mountPath: /import
              name: import
            - mountPath: /metrics
              name: metrics
          env:
            - name: PUSHGATEWAY_BASE_URL
              value: {{ .Values.metrics.pushgatewayUrl | quote }}
            - name: JOB_NAME
              value: {{ include "sophora-repo-import.fullname" . | quote }}
            {{- if .Values.metrics.authentication.secret.name }}
            - name: PUSHGATEWAY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metrics.authentication.secret.name | quote }}
                  key: {{ .Values.metrics.authentication.secret.usernameKey | quote }}
            - name: PUSHGATEWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metrics.authentication.secret.name | quote }}
                  key: {{ .Values.metrics.authentication.secret.usernameKey | quote }}
            {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      volumes:
        - name: import
          emptyDir: {}
        - name: importer-config
          configMap:
            name: {{ include "sophora-repo-import.fullname" . }}
        - name: metrics
          emptyDir: {}
