apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sophora-repo-import.fullname" . }}
  labels: {{- include "sophora-repo-import.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      shareProcessNamespace: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.repoDownload.zipViaHttp.zipUrls }}
        - name: zip-via-http-downloader
          image: "{{ .Values.repoDownload.zipViaHttp.image.repository }}:{{ .Values.repoDownload.zipViaHttp.image.tag }}"
          imagePullPolicy: {{ .Values.repoDownload.zipViaHttp.image.pullPolicy }}
          volumeMounts:
            - mountPath: /import
              name: import
          env:
            - name: REPO_ZIP_URLS
              value: {{ include "sophora-repo-import.utils.joinListWithSpace" .Values.repoDownload.zipViaHttp.zipUrls | quote }}
            - name: HTTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaHttp.usernameKey | quote }}
                  name: {{ .Values.repoDownload.zipViaHttp.secretName | quote }}
            - name: HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaHttp.passwordKey }}
                  name: {{ .Values.repoDownload.zipViaHttp.secretName | quote }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |-
             mkdir dl;
             cd dl;
             for REPO_ZIP_URL in $REPO_ZIP_URLS; do
               wget -q --user="${HTTP_USERNAME}" --password="${HTTP_PASSWORD}" $REPO_ZIP_URL;
               echo "Downloaded $REPO_ZIP_URL"
             done
             for file in `ls *.zip`; do unzip $file; done
             rm *.zip;
             mkdir -p /import/admin/incoming
             mkdir -p /import/temp
             mkdir -p /import/admin/success
             mkdir -p /import/admin/failure
             {{ if eq .Values.debugMode false }}mv * /import/admin/incoming{{ end }}
             echo "Copied data to import into local directory /import/admin/incoming"
             tree /import/admin/incoming
        {{- end }}
        {{- if .Values.repoDownload.zipViaS3.zipPaths }}
        - name: zip-via-s3-downloader
          image: "{{ .Values.repoDownload.zipViaS3.image.repository }}:{{ .Values.repoDownload.zipViaS3.image.tag }}"
          imagePullPolicy: {{ .Values.repoDownload.zipViaS3.image.pullPolicy }}
          volumeMounts:
            - mountPath: /import
              name: import
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaS3.accessKeyIdKey }}
                  name: {{ .Values.repoDownload.zipViaS3.secretName }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.repoDownload.zipViaS3.secretAccessKeyKey }}
                  name: {{ .Values.repoDownload.zipViaS3.secretName }}
            - name: S3_ENDPOINT
              value: {{ .Values.repoDownload.zipViaS3.s3Endpoint }}
            - name: S3_NAME
              value: {{.Values.repoDownload.zipViaS3.bucketName }}
            - name: S3_FILE_PATHS
              value: {{ include "sophora-repo-import.utils.joinListWithSpace" .Values.repoDownload.zipViaS3.zipPaths | quote }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |-
              mkdir dl;
              cd dl;
              for S3_FILE_PATH in $S3_FILE_PATHS; do
               aws --endpoint="$S3_ENDPOINT" s3 cp "s3://$S3_NAME$S3_FILE_PATH" ./
               echo "Downloaded $S3_FILE_PATH"
              done
              for file in `ls *.zip`; do unzip $file; done
              rm *.zip;
              mkdir -p /import/admin/incoming
              mkdir -p /import/temp
              mkdir -p /import/admin/success
              mkdir -p /import/admin/failure
              {{ if eq .Values.debugMode false }}mv * /import/admin/incoming{{ end }}
              echo "Copied data to import into local directory /import/admin/incoming"
              tree /import/admin/incoming
        {{- end }}
      containers:
        - name: importer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |- {{- .Files.Get "run-importer.sh" | nindent 14 }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaOptions }}
            - name: SOPHORA_CLIENT_SERVERCONNECTION_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{.Values.sophora.authentication.secret.usernameKey}}
                  name: {{.Values.sophora.authentication.secret.name}}
            - name: SOPHORA_CLIENT_SERVERCONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{.Values.sophora.authentication.secret.passwordKey}}
                  name: {{.Values.sophora.authentication.secret.name}}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: importer-config
              mountPath: /sophora/application.yml
              subPath: application.yml
            - name: import
              mountPath: /import
        - name: process-watcher
          image: "alpine:latest"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |- {{ .Files.Get "wait-for-empty-dir.sh" | nindent 14 }}
          volumeMounts:
            - mountPath: /import
              name: import
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      volumes:
        - name: import
          emptyDir: {}
        - name: importer-config
          configMap:
            name: {{ include "sophora-repo-import.fullname" . }}
