apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sophora-server.propertiesName" . }}
  labels:
  {{- include "sophora-server.labels" . | nindent 4 }}
data:
  sophora.properties: |- {{ toString (required "A valid sophora.properties configuration needs to be provided." .Values.sophora.server.properties) | nindent 4  }}
