apiVersion: v2
name: sophora-seo-check
description: Sophora SEO Check
type: application
version: 1.1.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API."

appVersion: 4.12.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-seo-check
home: https://subshell.com/sophora/modules/sophora-seo-check104.html
icon: https://subshell.com/logos/sophora-seo-check100~1x1.1683631781182.png