apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sophora-ugc-multimedia.fullname" . }}-logback
  labels:
  {{- include "sophora-ugc-multimedia.labels" . | nindent 4 }}
data:
  logback.xml: |
    {{- .Values.sophora.ugcMultimedia.logback | nindent 4}}
