apiVersion: v1
kind: Service
metadata:
  name: {{ include "sophora-ugc-multimedia.fullname" . }}-webapp
  labels:
    {{- include "sophora-ugc-multimedia.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.webapp.type }}
  loadBalancerIP: {{ .Values.service.webapp.loadBalancerIP }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "sophora-ugc-multimedia.selectorLabels" . | nindent 4 }}
