{{- if and .Values.grpcHttproute.enabled .Values.sophora.grpcApi.enabled -}}
  {{- $fullName := include "sophora-server.fullname" . -}}
  {{- $routeName := printf "%s-grpc" ($fullName | trunc 58 | trimSuffix "-") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $routeName }}
  labels: {{ include "sophora-server.topLevelLabels" . | nindent 4 }}
  {{- with .Values.grpcHttproute.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.grpcHttproute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.grpcHttproute.hostnames }}
  hostnames:
  {{- range .Values.grpcHttproute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ .Values.sophora.server.ports.grpc }}
      {{- with .Values.grpcHttproute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grpcHttproute.filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
