{{- if and .Values.grpcRoute.enabled .Values.sophora.grpcApi.enabled -}}
  {{- $fullName := include "sophora-server.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $fullName }}
  labels: {{ include "sophora-server.topLevelLabels" . | nindent 4 }}
  {{- with .Values.grpcRoute.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.grpcRoute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.grpcRoute.hostnames }}
  hostnames:
  {{- range .Values.grpcRoute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ .Values.sophora.server.ports.grpc }}
      {{- with .Values.grpcRoute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grpcRoute.filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
