{{- if and .Values.serverModeLabeler.enabled .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{- include "common.safeSuffixFullName" (list . "serverModeLabeler") | nindent 4 }}
  labels: {{- include "sophora-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sophora-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sophora-server.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
