nameOverride: test-deskclient-downloads

# Builds a updatesite url with the following scheme:
# https://software.subshell.com/download-sophora/4/deskclient-4.1.0/sophora-deskclient-4.1.0-unified-deskclient-downloads.zip
sophoraDownload:
  baseUrl: "https://software.subshell.com/download-unified-sophora"
  version: "4.1.6"
  identifier: "unified-sophora-test"
  secretName: "sophora-repository-download-credentials"

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: nginx
  hosts:
    - path: "/"
      pathType: Prefix
      host: "test.com"
  enabled: true

resources:
  limits:
    cpu: "500m"
    memory: "100M"
  requests:
    cpu: "250m"
    memory: "25M"
