{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "o-neko.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels: {{- include "o-neko.labels" . | nindent 4 }}
  name: {{ $fullName }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- range .Values.httpRoute.hostnames }}
  hostnames:
    - {{ required "A hostname for the HTTPRoute must be provided in .Values.httpRoute.hostnames" . | quote }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: 8080
      {{- with .Values.httpRoute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.httpRoute.filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
