# Default values for courier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.subshell.com/auxi/auxi-documentation
  pullPolicy: Always
  tag: # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []

podAnnotations: {}

fullnameOverride:
nameOverride:

service:
  annotations: {}
  type: LoadBalancer
  port: 80

ingress:
  ingressClassName: nginx
  tls:
  hosts:
  annotations: {}

resources: {}

env: {}
