apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophora-image-update-service
  labels:
    {{- include "sophora-image-update-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sophora-image-update-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/update-service-config.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sophora-image-update-service.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sophora-image-service.serviceAccountName" . }}
      containers:
        - name: image-update-service
          image: "{{ .Values.image.updateService.repository }}:{{ .Values.image.updateService.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /app/config
              name: config
          env:
            {{- include "sophora-image-service.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "sophora-image-update-service.name" . }}
