apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sophora-image-update-service.name" . }}
  labels:
  {{- include "sophora-image-update-service.labels" . | nindent 4 }}
data:
  application.yaml: |- {{ toYaml (required "A valid application.yml config is required for update-service" .Values.sophora.configuration.updateService) | nindent 4 }}