apiVersion: v2
name: o-neko-catnip
description: A Helm chart for the O-Neko URL trigger
type: application
version: 1.3.5
appVersion: "1.3.2"
sources:
  - https://github.com/subshell/o-neko-catnip/
  - https://github.com/subshell/helm-charts/tree/main/charts/o-neko-catnip

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "added Artifacthub changelog annotation"
