apiVersion: v2
name: o-neko-catnip
description: A Helm chart for the O-Neko URL trigger
type: application
version: 1.4.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API"

appVersion: "1.3.2"
sources:
  - https://github.com/subshell/o-neko-catnip/
  - https://github.com/subshell/helm-charts/tree/main/charts/o-neko-catnip
