apiVersion: v2
name: o-neko-catnip
description: A Helm chart for the O-Neko URL trigger
type: application
version: 1.3.2
appVersion: "1.3.2"
sources:
- https://github.com/subshell/o-neko-catnip/

annotations:
  artifacthub.io/changes: |