# Default values for courier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.subshell.com/sophora-courier/base
  pullPolicy: Always
  tag: # Overrides the image tag whose default is the chart appVersion.

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  jolokiaPort: 1496
  jolokiaTargetPort: 1496

sophora:
  courier:
    logback: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration scan="true" scanPeriod="30 seconds" debug="false">

          <!-- https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml-->
          <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

          <property name="LOG_PATH" value="${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}"/>
          <property name="PATTERN" value="[%d{yyyy-MM-dd HH:mm:ss.SSSX,UTC}, %-5p] [%t] %m%n" />

          <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
              <encoder>
                  <pattern>${PATTERN}</pattern>
              </encoder>
          </appender>

          <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
              <encoder>
                  <pattern>${PATTERN}</pattern>
              </encoder>
              <file>${LOG_PATH}/sophora-courier.log</file>
              <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                  <fileNamePattern>${LOG_PATH}/sophora-courier.log.%d{yyyy-MM-dd}.gz</fileNamePattern>
                  <maxHistory>31</maxHistory>
              </rollingPolicy>
          </appender>

          <root level="WARN">
              <appender-ref ref="FILE"/>
              <appender-ref ref="STDOUT"/>
          </root>

          <logger name="com.subshell.sophora" level="INFO"/>
          <logger name="com.subshell.sophora.courier" level="DEBUG"/>
          <logger name="com.jcraft.jsch" level="ERROR"/>
          <logger name="org.springframework.web" level="INFO"/>


      </configuration>
    config:
      server:
        port: 8080

        sophora:
          serverUrl: "http://my-server:1196"
          urlServletPath: http://my-delivery.default.svc.cluster.local/system/servlet/urlService.servlet
          channel: presse
          retryIntervalInMs: 5000
          maxRetries: 5
          noRetryErrorMessage: "Fehler: E-Mail/Newsletter hat keinen Inhalt."

        preview:
          urlServletPath: http://my-delivery.default.svc.cluster.local/system/servlet/urlService.servlet
          userExternalId: preview-user-courier

        propertyNames:
          distributorName: customer:name
          publicDistributor: customer:public

        logging:
          config: "config/logback/logback.xml"
          path: "/logs/"

        mail:
          useDeliveryToGenerateTemplate: true
          sendIntervalMs: 1000
          maxQueueSize: 200
          host: 10.5.0.2
          port: 25
          safeMode:
            enabled: true
            whitelist:
              - someone@subshell.com


resources:
  requests:
    memory: "3G"
    cpu: "0.5"
  limits:
    memory: "3.5G"
    cpu: "2"

secret:
  name: courier-credentials
  key:
    courier:
      username: username
      password: password
    basicauth:
      username: username
      password: password
    mail:
      username: username
      password: password

updateStrategy:
  type: RollingUpdate

command:
  - "java"
  - "-Dlogging.config=config/logback/logback.xml"
  - "-Dspring.config.location=file:config/application/application.yml"
  - "-Djava.security.egd=file:/dev/./urandom"
  - "-Dsophora.sophoraUsername=${SOPHORA_USERNAME}"
  - "-Dsophora.sophoraPassword=${SOPHORA_PASSWORD}"
  - "-Dsophora.basicAuthUsername=${SOPHORA_BASICAUTH_USERNAME}"
  - "-Dsophora.basicAuthPassword=${SOPHORA_BASICAUTH_PASSWORD}"
  - "-Dmail.username=${MAIL_USERNAME}"
  - "-Dmail.password=${MAIL_PASSWORD}"
  - "-XX:MinRAMPercentage=50.0"
  - "-XX:MaxRAMPercentage=90.0"
  - "-XX:+AlwaysPreTouch"
  - "-jar"
  - "/sophora-courier.jar"