# Default values for courier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.subshell.com/sophora-courier/base
  pullPolicy: Always
  tag: # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []

podAnnotations: {}

javaOptions: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem"

service:
  annotations: {}
  type: LoadBalancer
  port:
  targetPort:
  jolokiaPort:
  jolokiaTargetPort:
  loadBalancerIP:

sophora:
  courier:
    logback: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration scan="true" scanPeriod="30 seconds" debug="false">

          <!-- https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml-->
          <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

          <property name="LOG_PATH" value="${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}"/>
          <property name="PATTERN" value="[%d{yyyy-MM-dd HH:mm:ss.SSSX,UTC}, %-5p] [%t] %m%n" />

          <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
              <encoder>
                  <pattern>${PATTERN}</pattern>
              </encoder>
          </appender>

          <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
              <encoder>
                  <pattern>${PATTERN}</pattern>
              </encoder>
              <file>${LOG_PATH}/sophora-courier.log</file>
              <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                  <fileNamePattern>${LOG_PATH}/sophora-courier.log.%d{yyyy-MM-dd}.gz</fileNamePattern>
                  <maxHistory>31</maxHistory>
              </rollingPolicy>
          </appender>

          <root level="WARN">
              <appender-ref ref="FILE"/>
              <appender-ref ref="STDOUT"/>
          </root>

          <logger name="com.subshell.sophora" level="INFO"/>
          <logger name="com.subshell.sophora.courier" level="DEBUG"/>
          <logger name="com.jcraft.jsch" level="ERROR"/>
          <logger name="org.springframework.web" level="INFO"/>


      </configuration>
    config:

resources:
  requests:
    cpu: 100m
    memory: 4Gi
  limits:
    cpu: 500m
    memory: 4Gi

nodeSelector:
  usage:

secret:
  name: courier-credentials
  key:
    courier:
      username:
      password:
    basicauth:
      username:
      password:
    mail:
      username:
      password:

env: {}
