apiVersion: v2
name: sophora-ai
description: Sophora AI
type: application
version: 2.1.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API"

appVersion: 1.5.5
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-ai
home: https://subshell.com/sophora/modules/sophora-ai100.html
icon: https://subshell.com/logos/sophora-ai106~1x1.1728311176867.png
