{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "o-neko-catnip.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels: {{- include "o-neko-catnip.labels" . | nindent 4 }}
  name: {{ $fullName }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- range .Values.httpRoute.hostnames }}
  hostnames:
    - {{ required "A hostname for the HTTPRoute must be provided in .Values.httpRoute.hostnames" . | quote }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: 8080
      matches:
        - path:
            type: {{ .Values.httpRoute.pathMatchType | default "PathPrefix" }}
            value: {{ .Values.httpRoute.pathValue | default "/" }}
{{- end }}
