apiVersion: v2
name: sophora-media-finder
description: A Helm chart for Sophora Media Finder
type: application
version: 0.3.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API"

appVersion: "5.x"
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-media-finder
home: https://subshell.com/sophora/modules/sophora-smf100.html
icon: https://subshell.com/logos/sophora-media-finder100~1x1.1728311057357.png
