apiVersion: v2
name: sophora-image-ai
description: Sophora Image AI
type: application
version: 2.2.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API"

appVersion: 5.1.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-image-ai
home: https://subshell.com/sophora/modules/sophora-image-ai100.html
icon: https://subshell.com/logos/sophora-image-ai104~1x1.1692715050244.png
