apiVersion: v2
name: o-neko
description: A Helm chart for O-Neko
type: application
version: 2.1.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API"

appVersion: "1.8.2"
sources:
  - https://github.com/subshell/o-neko/
  - https://github.com/subshell/helm-charts/tree/main/charts/o-neko
