apiVersion: v2
name: o-neko
description: A Helm chart for O-Neko
type: application
version: 2.0.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated O-Neko to 1.8.2"

appVersion: "1.8.2"
sources:
  - https://github.com/subshell/o-neko/
  - https://github.com/subshell/helm-charts/tree/main/charts/o-neko
