apiVersion: v2
name: sophora-indexing-service
description: Sophora Indexing Service (SISI)
type: application
version: 1.6.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added HTTPRoute support for Gateway API."

appVersion: '5.4.1'
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-indexing-service
home: https://subshell.com/sophora/modules/sophora-indexing-service100.html
icon: https://subshell.com/logos/sophora-indexing-service104~1x1.1683632384186.png
