apiVersion: v2
name: sophora-linkchecker
description: Sophora Link Checker
type: application
version: 0.1.1
appVersion: 6.0.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-linkchecker
