apiVersion: v1
kind: Service
metadata:
  name: {{ include "auxi-documentation.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "auxi-documentation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      name: web
  selector:
    app: {{ include "auxi-documentation.fullname" . }}
