apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auxi-documentation.fullname" . }}
  {{- with .Values.podAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "auxi-documentation.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "auxi-documentation.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "auxi-documentation.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{ if .Values.env -}}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
