apiVersion: v2
name: sophora-contentapi
description: Sophora Content API
type: application
version: 1.0.0
appVersion: 6.0.0
sources:
  - https://github.com/subshell/helm-charts/tree/main/charts/sophora-contentapi
