apiVersion: v2
name: sophora-metadata-supplier
description: Sophora Metadata Supplier (SMS)
type: application
version: 1.3.3
appVersion: '4.14.0'

annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: fixed description of alert
