apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sophora-updatesite.fullname" . }}
  labels:
    {{- include "sophora-updatesite.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name updatesite;
        root /usr/share/nginx/html;

        autoindex on;
        location / {
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }
    }