apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "courier.fullname" . }}
  {{- with .Values.podAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "courier.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "courier.fullname" . }}
  serviceName: {{ include "courier.fullname" . }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  template:
    metadata:
      labels:
        app: {{ include "courier.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SOPHORA_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.key.courier.username }}
                  name: {{ .Values.secret.name }}
            - name: SOPHORA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.key.courier.password }}
                  name: {{ .Values.secret.name }}
            - name: SOPHORA_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.key.basicauth.username }}
                  name: {{ .Values.secret.name }}
            - name: SOPHORA_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.key.basicauth.password }}
                  name: {{ .Values.secret.name }}
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.key.mail.username }}
                  name: {{ .Values.secret.name }}
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.key.mail.password }}
                  name: {{ .Values.secret.name }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1496
            - containerPort: 8080
          volumeMounts:
            - name: {{ include "courier.fullname" . }}-logback-config
              mountPath: /config/logback
            - name: {{ include "courier.fullname" . }}-application-yml
              mountPath: /config/application
            - name: datadog
              mountPath: /datadog
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "courier.fullname" . }}-logback-config
          configMap:
            name: {{ include "courier.fullname" . }}-logback
        - name: {{ include "courier.fullname" . }}-application-yml
          configMap:
            name: {{ include "courier.fullname" . }}-config
        - name: datadog
          persistentVolumeClaim:
            claimName: datadog-pvc
            readOnly: true
